### ISSUE TITLE
[Documentation Request] - Add the new hackathons for the 2019/2020 season

### ISSUE THREAD

**Issue by johnkahn** [AmericanAirlines/Flight-Engine#1]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

We should put the new hackathons for the 2019/2020 season.

We should also switch the order, so the current hackathons are above the past ones.

We should also switch from being single year to multiple year.
> E.g. ~2018~ **2017/2018**

**Comment by SpencerKaiser** [comment]
@johnkahn I finished making the above updates, but not are I agree with the last one... I think that would end up making things more confusing. Thoughts?
