### ISSUE TITLE
[Feature Request] - Implement /airport to retrieve airport details

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Flight-Engine#13]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

A user should be able to retrieve details for a given airport using the airport code.

## Describe the solution you'd like

A user should be able to make a request to `/airport` with a `code` parameter to retrieve details for that airport.

**Comment by SpencerKaiser** [comment]
@johnkahn as part of this change, what do you think about removing rich details of an airport (lat/lon, name, etc.) from the `/flights` response? It'd be extra work to remove it, but it might make the response a little more manageable to make this endpoint a little more meaningful.

**Comment by johnkahn** [comment]
Yeah, sounds good, just reference the airport code.
