### ISSUE TITLE
[Feature Request] - Remove Lodash

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Flight-Engine#35]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

We should be using es6 functionality instead of relying on Lodash

## Describe the solution you'd like

Remove lodash and replace all usage with appropriate es6 functionality

**Comment by teddywagner** [comment]
I have gone through the files in this repository and do not see any references to Lodash in any of the code.

**Comment by SpencerKaiser** [comment]
Thanks for pointing that out, @teddywagner!!
