### ISSUE TITLE
[Documentation Request] - Include example data in README

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Flight-Engine#4]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

The `README` should provide more of a hook for why it should be used.

## Describe the solution you'd like

The `README` should include sample info like an example of the flights or the endpoints that can be used

## Additional context

Look at similar data generation projects to get some good ideas on what to include and how to structure it.

**Comment by charliealbright** [comment]
README includes sample requests/responses now
